version: '3.9'

services:
  condominio-nginx:
    image: nginx:alpine
    container_name: condominio-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - condominio-frontend
      - condominio-backend
    networks:
      - internal
      - public

  condominio-backend:
    build:
      context: ./condominio_BackEnd
    container_name: condominio-backend
    expose:
      - "9000"
    depends_on:
      - condominio-postgres
      - proxy
    networks:
      - internal
      - proxy-net

  condominio-frontend:
    build:
      context: ./condominio_Frontend
    container_name: condominio-frontend
    expose:
      - "80"
    networks:
      - internal

  condominio-postgres:
    image: postgres:16-alpine
    container_name: condominio-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  proxy:
    image: sameersbn/squid:latest
    container_name: proxy
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
    ports:
      - "3128:3128"
    networks:
      - proxy-net
      - public
networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
  proxy-net:
    internal: true
    driver: bridge

volumes:
  postgres_data:

